const MAX_CELL_LENGTH = 50000;
const REALM_BASE_URL = "https://webhooks.mongodb-realm.com/api/client/v2.0/app";
// replace next 2 with appropriate per env
const REALM_APP_ID = "posts-moderation-AUTOGENERATED-SUFFIX";
const REALM_WEBHOOK_SECRET = "UPDATE-WITH-PER-ENV-SECRET";

function postToRow(post) {
  return [
    post.title,
    post.link,
    post.content.length > MAX_CELL_LENGTH
      ? post.content.substr(0, MAX_CELL_LENGTH)
      : post.content,
    post.createdAt,
    post.updatedAt,
  ];
}

function getPosts() {
  var response = UrlFetchApp.fetch(
    `${REALM_BASE_URL}/${REALM_APP_ID}/service/http-service/incoming_webhook/get-posts?secret=${REALM_WEBHOOK_SECRET}`
  );

  var postsText = response.getContentText();
  var posts = JSON.parse(postsText).map(postToRow);

  var sheet = SpreadsheetApp.getActiveSheet();
  if (posts.length) {
    sheet.getRange(2, 1, posts.length, posts[0].length).setValues(posts);
  } else {
    sheet.getRange(2, 1).setValue("No posts");
  }
}
